[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd /app/GuardianDashBaordAI && node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"