name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GuardianDashBaordAI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: GuardianDashBaordAI/package.json

      - name: Install deps
        run: npm install

      - name: Lint (optional)
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.cjs ] || [ -f .eslintrc.json ]; then npm run lint || true; fi

      - name: Run tests
        env:
          MONGO_URI: mongodb://127.0.0.1:27017/test_db_fake # not used because we don't require real operations in current tests
          JWT_SECRET: tempsecret
        run: npm test -- --ci --reporters=default --coverage=false

  # Optional deploy job template (disabled by default)
  # deploy:
  #   needs: build-test
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Deploy over SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USER }}
  #         key: ${{ secrets.VPS_SSH_KEY }}
  #         script: |
  #           cd /var/www/guardian/DASHBOARD-GUARDIAN
  #           git pull origin main
  #           ./scripts/deploy.sh
